// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";

function make(title, author, text) {
  return {
          title: title,
          author: author,
          text: text
        };
}

function title(t) {
  return t.title;
}

function author(t) {
  return t.author;
}

function text(t) {
  return t.text;
}

var Post = {
  make: make,
  title: title,
  author: author,
  text: text
};

var posts = [
  {
    title: "The Razor's Edge",
    author: "W. Somerset Maugham",
    text: [
      "\"I couldn't go back now. I'm on the threshold. I see vast lands of the spirit stretching out before me,\n    beckoning, and I'm eager to travel them.\"",
      "\"What do you expect to find in them?\"",
      "\"The answers to my questions. I want to make up my mind whether God is or God is not. I want to find out why\n    evil exists. I want to know whether I have an immortal soul or whether when I die it's the end.\""
    ]
  },
  {
    title: "Ship of Destiny",
    author: "Robin Hobb",
    text: [
      "He suddenly recalled a callow boy telling his tutor that he dreaded the sea voyage home, because he would have\n        to be among common men rather than thoughtful acolytes like himself. What had he said to Berandol?",
      "\"Good enough men, but not like us.\"",
      "Then, he had despised the sort of life where simply getting from day to day prevented a man from ever taking\n        stock of himself. Berandol had hinted to him then that a time out in the world might change his image of folk\n        who labored every day for their bread. Had it? Or had it changed his image of acolytes who spent so much time in\n        self-examination that they never truly experienced life?"
    ]
  },
  {
    title: "A Guide for the Perplexed: Conversations with Paul Cronin",
    author: "Werner Herzog",
    text: ["Our culture today, especially television, infantilises us. The indignity of it kills our imagination. May I propose a Herzog dictum? Those who read own the world. Those who watch television lose it. Sitting at home on your own, in front of the screen, is a very different experience from being in the communal spaces of the world, those centres of collective dreaming. Television creates loneliness. This is why sitcoms have added laughter tracks which try to cheat you out of your solitude. Television is a reflection of the world in which we live, designed to appeal to the lowest common denominator. It kills spontaneous imagination and destroys our ability to entertain ourselves, painfully erasing our patience and sensitivity to significant detail."]
  }
];

function makeDiv(param) {
  return document.createElement("div");
}

function makeScaledHeading(tag) {
  return document.createElement(tag);
}

function makePara(param) {
  return document.createElement("p");
}

function makeButton(param) {
  return document.createElement("button");
}

function makeSpecialElement(tag) {
  return document.createElement(tag);
}

function makeTextNode(text) {
  return document.createTextNode(text);
}

function addClass(element, className) {
  element.classList.add(className);
  return element;
}

function addId(element, idName) {
  element.id = idName;
  return element;
}

function addText(element, text) {
  element.innerText = text;
  return element;
}

function toString(index) {
  return String(index);
}

function getElementById(id) {
  return document.getElementById(id);
}

function makeDeleteNotificationComponent(index, title, author, deletedPost) {
  var timeOutId = setTimeout((function (param) {
          var id = "block-" + String(index);
          var element = document.getElementById(id);
          return document.body.removeChild(element);
        }), 10000);
  var div = addClass(addClass(addId(document.createElement("div"), "block-" + String(index)), "post-deleted"), "pt-1");
  var para = addText(addClass(document.createElement("p"), "text-center"), "This post from ");
  var specialElement = addText(document.createElement("em"), title + " by " + author);
  para.appendChild(specialElement);
  para.appendChild(document.createTextNode(" will be permanently removed in 10 seconds."));
  div.appendChild(para);
  var buttonsDiv = addClass(document.createElement("div"), "flex-center");
  var restoreButton = addText(addClass(addClass(addClass(addId(document.createElement("button"), "block-restore-" + String(index)), "button"), "button-warning"), "mr-1"), "Restore");
  restoreButton.addEventListener("click", (function (param) {
          var id = "block-" + String(index);
          var element = document.getElementById(id);
          clearTimeout(timeOutId);
          return document.body.replaceChild(deletedPost, element);
        }));
  var immediateDeleteButton = addText(addClass(addClass(addId(document.createElement("button"), "block-delete-immediate-" + String(index)), "button"), "button-danger"), "Delete Immediately");
  immediateDeleteButton.addEventListener("click", (function (param) {
          var id = "block-" + String(index);
          var element = document.getElementById(id);
          clearTimeout(timeOutId);
          return document.body.removeChild(element);
        }));
  buttonsDiv.appendChild(restoreButton);
  buttonsDiv.appendChild(immediateDeleteButton);
  div.appendChild(buttonsDiv);
  var progressBar = addClass(document.createElement("div"), "post-deleted-progress");
  div.appendChild(progressBar);
  return div;
}

function makePostComponent(index, post) {
  var div = addClass(addId(document.createElement("div"), "block-" + String(index)), "post");
  var heading = addText(document.createElement("h2"), post.title);
  var subHeading = addText(document.createElement("h3"), post.author);
  div.appendChild(heading);
  div.appendChild(subHeading);
  Belt_Array.forEach(post.text, (function (text) {
          var para = addText(addClass(document.createElement("p"), "post-text"), text);
          return div.appendChild(para);
        }));
  var deleteButton = addText(addClass(addClass(addId(document.createElement("button"), "block-delete-" + String(index)), "button"), "button-danger"), "Remove this post");
  deleteButton.addEventListener("click", (function (param) {
          var id = "block-" + String(index);
          var postElement = document.getElementById(id);
          document.body.replaceChild(makeDeleteNotificationComponent(index, post.title, post.author, postElement), postElement);
          
        }));
  div.appendChild(deleteButton);
  return div;
}

function onLoadRenderPosts(posts) {
  return Belt_Array.forEachWithIndex(posts, (function (index, post) {
                return document.body.appendChild(makePostComponent(index, post));
              }));
}

onLoadRenderPosts(posts);

export {
  Post ,
  posts ,
  makeDiv ,
  makeScaledHeading ,
  makePara ,
  makeButton ,
  makeSpecialElement ,
  makeTextNode ,
  addClass ,
  addId ,
  addText ,
  toString ,
  getElementById ,
  makeDeleteNotificationComponent ,
  makePostComponent ,
  onLoadRenderPosts ,
  
}
/*  Not a pure module */
